import dewalt_dcd991nt from "./assets/products-img/dewalt_dcd991nt.png";
import bohrschrauber from "./assets/products-img/bohrschrauber.png";
import buerostuhl from "./assets/products-img/buerostuhl.png";
import Elba from "./assets/products-img/Elba.png";
import etikettendrucker from "./assets/products-img/etikettendrucker.png";
import kreide_boettcherag_100_stueck from "./assets/products-img/kreide_boettcherag_100_stueck.png";
import mesh_line_drehbar from "./assets/products-img/mesh_line_drehbar.png";
import Brother from "./assets/products-img/Brother.png";
import p2apple_ipad_air_2022 from "./assets/products-img/p2apple_ipad_air_2022.png";
import rollcontainer from "./assets/products-img/rollcontainer.png";
import tresorburg from "./assets/products-img/tresor_burg-waechter_pointsafe.png";
import businesstrolley from "./assets/products-img/businesstrolley.png";
export const categories = [
  {
    id: 1,
    title: "Alle Kategorien",
  },
  {
    id: 2,
    title: "Bürobedarf",
  },
  {
    id: 3,
    title: "Papiere & Etiketten",
  },
  {
    id: 4,
    title: "Schreiben ",
  },
  {
    id: 5,
    title: "Verpackung",
  },
  {
    id: 6,
    title: "Präsentation",
  },
  {
    id: 7,
    title: "Druckerpatronen",
  },
  {
    id: 8,
    title: "Elektronik",
  },
  {
    id: 9,
    title: "Büromöbel",
  },
  {
    id: 10,
    title: "Lebensmittel",
  },
  {
    id: 11,
    title: "Werkzeug ",
  },
];

export const products = [
  {
    id: 1,
    title: "DeWalt Akku-Bohrschrauber DCD791P218V",
    brand: "DeWalt",
    price: 282,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>DeWalt DCD791P218V / 5,0Ah, mit 2 Akkus und Koffer</h6><br></br><p>Merkmale:<br>Akkuspannung: 18 V<br>Akku-Lieferumfang: 2 Akkus<br>Ladegerät: mit Ladegerät<br>----------------------------------------<br>weitere Produktinformationen:<br>Akkukapazität: 5,0Ah<br>Verwendung: Schrauben und Bohren<br>Drehmomentstufen: 15 + 1 Bohrstufe<br>Drehmoment weich: 27 Nm<br>Drehmoment hart: 70 Nm<br>Bohrfutterspannweite: 1,5-13 mm<br>Getriebe: 2 Gang<br>Drehzahl bis: 2000 U/min<br>Gewicht: 1,7 kg<br>Lieferung: inkl. 2x Akku, Schnellladegerät, Transportkoffer T STAK-Box<br>----------------------------------------<br>sonstiges: mit leuchtstarker LED, äußerst kompakte, ausbalancierte Bauweise mit geringem Gewicht, leicht dosierbare Schalterelektronik für exaktes Anbohren und präzises Schrauben, Problemloser Langzeiteinsatz durch Sicherheitselektronik (permanente Überprüfung von Akku-Temperatur, Stromentnahme und Entladeschutz)</p>",
    amount: 2,
    img: dewalt_dcd991nt,
    alt: "dewalt",
    available: "Sofort lieferbar",
    instock: "in-stock",
    sale: 0,
  },
  {
    id: 2,
    title: "Bosch Akku-Bohrschrauber GSR 18V-55, 18V",
    brand: "Bosch",
    price: 178,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>Akku-Bohrschrauber Bosch GSR 18V-55 Professional</h6><br><p>Kaufen Sie ein Bosch Professional 18V-Elektrowerkzeug&nbsp;über&nbsp;150 € (exkl. MwSt.) und erhalten Sie nach Registrierung auf https://www.bosch-professional.com/de/de/pro360/prodeals/ eine Prämie&nbsp;GRATIS dazu (siehe auch PDF Datenblatt).<br>----------------------------------------<br>Merkmale:<br>Akkuspannung: 18 V<br>Akku-Lieferumfang: 2 Akkus<br>Ladegerät: mit Ladegerät<br>----------------------------------------<br>weitere Produktinformationen:<br>Akkukapazität: 4,0Ah<br>Verwendung: Schrauben und Bohren<br>Drehmomentstufen: 20 + 1 Bohrstufe<br>Drehmoment weich: 28 Nm<br>Drehmoment hart: 55 Nm<br>Bohrfutterspannweite: 1,5-13 mm<br>Getriebe: 2 Gang<br>Drehzahl bis: 1750 U/min<br>Gewicht: 1 kg<br>Lieferung: inkl. 2x Akku ProCORE18V 4.0Ah, Schnellladegerät GAL 18V-40, Transportkoffer (L-BOXX 136)<br>----------------------------------------<br>sonstiges: für Arbeiten in Holz und Metall, mit bürstenlosem Motor für längere Werkzeuglebensdauer und höhere Akkulaufleistung, Electronic Motor Protection (EMP) schützt den Motor vor Überlastung</p>",
    amount: 1,
    img: bohrschrauber,
    alt: "mesh_line_drehbar",
    available: "Sofort lieferbar",
    instock: "in-stock",
    sale: 0,
  },
  {
    id: 3,
    title: "Etikettendrucker GG-image GG-D1200CW",
    brand: "G&G",
    price: 150,
    category: ["Bürobedarf", "Etikettendrucker"],
    desc: "<h6>etikettendrucker.webp</h6><br><p>• Leistungsstarker DHL-Etikettendrucker<br>• Bequem per App ansteuerbar<br>• Ideal für den Druck von DHL/UPS/DPD/Hermes/etc.-Versandaufklebern eignet<br>• Druckgeschwindigkeit: 120 mm/Sekunde<br>• Inklusive Cutter<br>----------------------------------------<br>Merkmale:<br>Schnittstelle: USB, Bluetooth<br>Drucktechnik: Thermodirekt<br>Ausführung: mit Barcodedruck<br>Druckhöhe: 104 mm<br>----------------------------------------<br>weitere Produktinformationen:<br>Etikettenhöhe: bis 105 mm<br>Medientypen: Einzel- oder Endlosetiketten mit oder ohne Reflexmarke, Endlosbelegpapier<br>Druckgeschwindigkeit: 120 mm/Sekunde<br>Druckauflösung: 203 x 203 dpi<br>Farbe: weiß<br>Maße: (BxHxT) 22,2 x 9,2 x 10,5 cm<br>Lieferung: inkl. USB-Kabel<br>----------------------------------------<br>sonstiges: Etikettendesigns können individuell per App erstellt werden</p>",
    amount: 4,
    img: etikettendrucker,
    alt: "etikettendrucker",
    available: "Sofort lieferbar",
    instock: "in-stock",
    sale: 0,
  },
  {
    id: 4,
    title: "Stiftehalter Böttcher-AG Mesh Line, drehbar",
    brand: "Böttcher-AG",
    price: 253,
    category: ["Bürobedarf", "Stiftehalter"],
    desc: "<h6>Stiftehalter Böttcher-AG Mesh Line, drehbar</h6><br><p>Praktischer Stiftehalter mit 7 Fächern<br>• Aus schwarzem und robustem&nbsp;Metalldraht<br>• Leichte Reinigung dank glatter Oberfläche<br>• Jederzeit alles nötige griffbereit<br>----------------------------------------<br>Merkmale:<br>Material: Metalldraht<br>Farbe: schwarz<br>Ausführung: drehbar<br>----------------------------------------<br>weitere Produktinformationen:<br>Fächeranzahl: 7 Fächer<br>Maße: 17,5 x 11 cm (ØxH)</p>",
    amount: 1,
    img: mesh_line_drehbar,
    alt: "mesh_line_drehbar",
    available: "Sofort lieferbar",
    instock: "in-stock",
    sale: 0,
  },
  {
    id: 5,
    title: "Böttcher-AG H-8078F-2/1322 Bürostuhl",
    brand: "Böttcher-AG",
    price: 118,
    category: ["Stühle", "Bürobedarf"],
    desc: "<h6>Bürostuhl Böttcher-AG H-8078F-2/1322</h6><br><p>• Wippmechanik - einstellbar auf das Körpergewicht<br>• Muldensitz für optimale Unterstützung des Beckens<br>• Rückenlehne mit atmungsaktiver Netzbespannung<br>----------------------------------------<br>Merkmale:<br>Belastbarkeit: bis 120 kg<br>Bezug: Stoff, Netz<br>Farbe: schwarz<br>Armlehnenausführung: feste Armlehnen<br>----------------------------------------<br>weitere Produktinformationen:<br>Materialzusammensetzung: Stoff 100 % Polyester, Netz 100 % Polyester<br>empfohlene Sitzdauer: 6 Stunden/Tag<br>Sitztechnik: Wippmechanik<br>Sitzart: Muldensitz<br>Sitzgröße: 48 x 48 cm (BxT)<br>Sitzhöhenverstellung: 46 - 56 cm<br>Rückenlehnenhöhe: 48 cm<br>Fußkreuz: Kunststoff, verchromt<br>Rollen: Teppichbodenrollen<br>Lieferung: zerlegt</p>",
    amount: 1,
    img: buerostuhl,
    alt: "buerostuhl",
    available: "Sofort lieferbar",
    instock: "in-stock",
    sale: 0,
  },
  {
    id: 6,
    title: "Kreide 100 Stück, Tafelkreide sortiert",
    brand: "Böttcher-AG",
    price: 7.5,
    category: ["Schreiben & Korrigieren"],
    desc: "<h6>Kreide 100 Stück, Tafelkreide sortiert</h6><br><p>• Runde Tafelkreide, 100 Stück im praktischen Karton<br>• Staubfrei, sandfrei, leicht abwischbar<br>• Gute Farbabgabe<br>----------------------------------------<br>Merkmale:<br>Ausführung: Tafelkreide<br>Farbe: farbig sortiert<br>Form: rund<br>----------------------------------------<br>weitere Produktinformationen:<br>Länge: 80 mm<br>Spitze: ungespitzt</p>",
    amount: 1,
    img: kreide_boettcherag_100_stueck,
    alt: "Kreide 100 Stück",
    available: "Sofort lieferbar",
    instock: "in-stock",
    sale: 0,
  },
  {
    id: 7,
    title: "Elba rado 81417 Hängeordner",
    brand: "DeWalt",
    price: 8.3,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>Hängeordner Elba 81417, rado, A4</h6><br><p>• Für die Hängeregistratur konzipiert, aber auch stehend verwendbar<br>• Mit einschiebbarem Hängebügel und metallgefasstem Griffloch<br>• Hebelmechanik mit Druckniederhalter<br>• Raumsparschlitze zur platzsparenden Archivierung<br>• Aus stabiler, Blauer Engel zertifizierter Hartpappe<br>----------------------------------------<br>Merkmale:<br>Format: A4<br>Ausführung: breit<br>----------------------------------------<br>weitere Produktinformationen:<br>Material: Hartpappe<br>Farbe: schwarz<br>Rückenbreite: 7,5 cm<br>Rückenschild: geklebt<br>Zertifikat: www.blauer-engel.de/uz56</p>",
    amount: 1,
    img: Elba,
    alt: "Hängeordner Elba",
    available: "Sofort lieferbar",
    instock: "in-stock",
    sale: 0,
  },
];
export const productsOnSale = [
  {
    id: 1,
    title: "Brother MFC L3750CDW Multifunktionsgerät",
    brand: "Brother",
    price: 478,
    category: ["Elektronik", "Computer"],
    desc: "<h6>Multifunktionsgerät Brother MFC L3750CDW</h6><br><p>Merkmale:<br>Ausführung: Farblaser, 4 in 1<br>Format bis: A4<br>Funktion: Drucker, Fax, Kopierer, Scanner<br>Schnittstelle: Apple AirPrint, Google Cloud Print, USB, LAN, WLAN<br>Eigenschaft: ADF, Duplex-Druck, mobiles Drucken<br>----------------------------------------<br>weitere Produktinformationen:<br>Drucktechnik: LED<br>Display: 9,3 cm Touchscreen-Farbdisplay<br>Druckvolumen: max. 30.000 Seiten/Monat, empfohlen bis 1.500 Seiten/Monat<br>Papiervorrat: 250 Blatt Kassette<br>Automatischer Dokumenteneinzug: 50 Blatt<br>Treiber: Windows 7 oder neuer, Mac OS X 10.11.6 oder neuer<br>Farbdrucker<br>Druck/Min.: s/w 24, farbig 24 Seiten, max. Auflösung: 2400 x 600dpi<br>Farbkopierer<br>Kopienvorwahl: 1-99, Zoom: 25% - 400%<br>Farbscanner<br>Typ: Flachbett, Einzug, Auflösung: 2400 x 1200dpi<br>Farbfax<br>Geschwindigkeit: 33600 bps, Speicher: 500 Seiten<br>Maße: (BxTxH) 41 x 47,5 x 41,4 cm<br>green-Aspekt: Energy Star - energiesparend<br>Garantie: 3 Jahre Herstellergarantie Vor-Ort<br>Lieferung: inkl. Toner, Netzkabel, Lieferung ohne Fax- und USB-Kabel<br>----------------------------------------<br>sonstiges: USB-Host, WiFi-Direct</p>",
    amount: 26,
    img: Brother,
    alt: "Multifunktionsgerät",
    available: ["Sofort lieferbar","badge style-2 consistent"],
    instock: "in-stock",
    sale: 20,
  },
  {
    id: 2,
    title: "Apple Tablet-PC iPad Air 2022 MM9E3FD",
    brand: "Apple",
    price: 690,
    category: ["Elektronik", "Computer"],
    desc: "<h6>Tablet-PC Apple iPad Air 2022 MM9E3FD</h6><br><p>• Liquid Retina Display und True Tone für mehr Details und Farben<br>• Produktiveres Arbeiten dank neuem M1 Chip mit Neural Engine<br>• Bestens ausgestattet für das digitale Klassenzimmer oder Homeoffice<br>• Facetime Frontkamera mit 12MP und praktischem Folgemodus<br>• Mit schneller &amp; sicherer Touch ID für sicheres Authentifizieren und Apple Pay<br>• Unterstützung für Magic Keyboard, Smart Keyboard Folio und Apple Pencil<br>----------------------------------------<br>Merkmale:<br>Modellreihe: iPad Air 2022<br>Displaygröße: 10,9 Zoll<br>Betriebssystem: Apple iPadOS<br>Kommunikation: WLAN<br>interner Speicher: 64 GB<br>----------------------------------------<br>weitere Produktinformationen:<br>Display: 10,9 Zoll / 27,69cm, Liquid Retina Display, Multi-Touchfunktion, True Tone<br>Bildauflösung: 2360 x 1640 Pixel bei 264 ppi<br>Prozessor: Apple M1 Chip, 8-Core CPU, 8-Core Grafik, Neural Engine<br>Arbeitsspeicher: 8 GB<br>Kamera (integriert): Frontkamera 12 MP, Rückkamera 12 MP<br>Kommunikation: WLAN 802.11a/b/g/n/ac/ax, Wi-Fi 6, Bluetooth 5.0<br>Anschlüsse: USB-C 3.1<br>Funktionen: WLAN-Internet, E-Mail, Video-/ Bilder- und Musikwiedergabe, Apple-Anwendungen, unterstützt den Apple Pencil 2.Generation<br>Akkutyp: Lithium-Polymer mit 28,6 Watt&shy;stunden<br>Farbe: blau<br>Maße: (BxHxT) 17,8 x 24,7 x 0,6 cm<br>Gewicht: 461 g<br>green-Aspekt: Energy Star<br>Lieferung: inkl. USB-C Power Adapter (Netzteil), USB-C-Ladekabel</p>",
    amount: 17,
    img: p2apple_ipad_air_2022,
    alt: "Apple Tablet-PC iPad Air",
    available: ["Bestpreis","badge  best"],
    instock: "in-stock",
    sale: 19,
  },
  {
    id: 3,
    title: "Rollcontainer FlexiSpot CB8",
    brand: "FlexiSpot",
    price: 214,
    category: ["Elektronik", "Computer"],
    desc: "<h6>Rollcontainer FlexiSpot CB8, Metall,schwarzmit 2 Schüben, abschließbar</h6><br><p>• Schlichtes Design mit abgerundeten Ecken &amp; glatten Kanten<br>----------------------------------------<br>Merkmale:<br>Farbe: schwarz<br>Ausführung: abschließbar, mit Schubladen<br>Material: Metall<br>----------------------------------------<br>weitere Produktinformationen:<br>Schließung: mit Zentralverschluss<br>Ausstattung: 2 Schübe<br>Tragkraft der Schübe: 20 kg<br>Griffe: Muldengriffe<br>Leichtlaufrollen: 4, 2 davon feststellbar<br>Maße: (BxHxT) 40 x 50 x 40 cm<br>Lieferung: montiert<br>Lieferung direkt ab Werk!<br>----------------------------------------<br>sonstiges: Schübe auf Teleskop-Auszügen, Stützrolle am unteren Schub</p>",
    amount: 16,
    img: rollcontainer,
    alt: "Rollcontainer FlexiSpot CB8",
    available: "",
    instock: "in-stock",
    sale: 29,
  },
  {
    id: 4,
    title: "Wenger Business-Trolley Patriot 2",
    brand: "Wenger",
    price: 148,
    category: ["Koffer", "Rucksäcke" ,"Taschen" ],
    desc: "<h6>Business-Trolley Wenger Patriot 2</h6><br><p>• Gepolstertes Fach für Laptops bis 17 Zoll<br>• Herausnehmbare Laptoptasche für Laptops bis 15,6 Zoll<br>• 1 Fach für Kleidung (Overnight-Funktion)<br>• Reißverschlussfächer, Handytasche und Stifthalter<br>• Ergonomischer Tragegriff und stabiler Standfuß<br>• Teleskopstange mit mehreren Längenstufen<br>• Leichtlaufrollen perfekt für enge Kurven und schmale Gänge<br>• Abschließbare Reißverschlüsse<br>----------------------------------------<br>Merkmale:<br>Größe: S (bis 56 cm), Handgepäck<br>Ausführung: Laptopfach<br>Material: Polyester<br>Farbe: schwarz<br>----------------------------------------<br>weitere Produktinformationen:<br>Verschluss: Reißverschluss<br>Laptopfach: bis 15,4 Zoll<br>Gewicht: 4,1 kg<br>Maße: 43 x 41 x 31 cm (BxHxT)<br>Garantie: 3 Jahre Herstellergarantie<br>----------------------------------------<br>sonstiges: 1 Hauptfach mit Einschubfächern für A4 Dokumente, 1 zusätzliches Reißverschlussfach außen</p>",
    amount: 9,
    img: businesstrolley,
    alt: "Wenger Business-Trolley Patriot 2",
    available: ["Empfehlen","badge style-2 recommend"],
    instock: "in-stock",
    sale: 10,
  },  {
    id: 5,
    title: "Burg-Wächter Tresor PointSafe P 2 E FS",
    brand: "Burg-Wächter",
    price: 223,
    category: [ "Büromöbel" , "Stahlschränke" ],
    desc: "<h6>Tresor Burg-Wächter PointSafe P 2 E FS</h6><br><p>Merkmale:<br>Funktion: Möbeltresor<br>Ausführung: biometrisch, mit Zahlenschloss<br>Schloss: Fingerabdruck, Elektronikschloss<br>Höhe: 25,5 cm<br>----------------------------------------<br>weitere Produktinformationen:<br>Außenmaß: 25,5 x 35 x 30 cm (HxBxT)<br>Innenmaß: 24,8 x 34,3 x 24,1 cm (HxBxT)<br>Türdurchgangsmaß: 18,8 x 23 cm (HxB)<br>Volumen: 20,5 Liter<br>Gewicht: 14 kg<br>Fächer: 2<br>Farbe: schwarz<br>Bodenverankerung: vorgerichtet für Rückwand- und Bodenverankerung inkl. Verankerungsmaterial<br>Lieferung: inkl. Befestigungsmaterial, Batterien (4x AA), einen Schlüssel zur mechanischen Notöffnung<br>----------------------------------------<br>sonstiges: einwandiger Korpus und doppelwandige Tür, einseitige Verriegelung durch massive 22mm starke Rundbolzen, Elektronik-Zahlenschloss mit General- und Benutzercode, Speicherung von bis zu 5 verschiedenen Fingerabdrücken, herausnehmbarer Fachboden, geeignet für die Aufbewahrung von Dokumenten aus Papier und Wertgegenständen, sowie Speichermedien</p>",
    amount: 19,
    img: tresorburg,
    alt: "Burg-Wächter Tresor PointSafe",
    available: "",
    instock: "in-stock",
    sale: 20,
  },
];
