export const categories = [
  {
    id: 1,
    title: "Alle Kategorien",
  },
  {
    id: 2,
    title: "Bürobedarf",
  },
  {
    id: 3,
    title: "Papiere & Etiketten",
  },
  {
    id: 4,
    title: "Schreiben ",
  },
  {
    id: 5,
    title: "Verpackung",
  },
  {
    id: 6,
    title: "Präsentation",
  },
  {
    id: 7,
    title: "Druckerpatronen",
  },
  {
    id: 8,
    title: "Elektronik",
  },
  {
    id: 9,
    title: "Büromöbel",
  },
  {
    id: 10,
    title: "Lebensmittel",
  },
  {
    id: 11,
    title: "Werkzeug ",
  },
];
export const products = [
  {
    id: 1,
    title: "DeWalt Akku-Bohrschrauber DCD791P218V",
    brand: "DeWalt",
    price: 282,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>DeWalt DCD791P218V / 5,0Ah, mit 2 Akkus und Koffer</h6><br></br><p>Merkmale:<br>Akkuspannung: 18 V<br>Akku-Lieferumfang: 2 Akkus<br>Ladegerät: mit Ladegerät<br>----------------------------------------<br>weitere Produktinformationen:<br>Akkukapazität: 5,0Ah<br>Verwendung: Schrauben und Bohren<br>Drehmomentstufen: 15 + 1 Bohrstufe<br>Drehmoment weich: 27 Nm<br>Drehmoment hart: 70 Nm<br>Bohrfutterspannweite: 1,5-13 mm<br>Getriebe: 2 Gang<br>Drehzahl bis: 2000 U/min<br>Gewicht: 1,7 kg<br>Lieferung: inkl. 2x Akku, Schnellladegerät, Transportkoffer T STAK-Box<br>----------------------------------------<br>sonstiges: mit leuchtstarker LED, äußerst kompakte, ausbalancierte Bauweise mit geringem Gewicht, leicht dosierbare Schalterelektronik für exaktes Anbohren und präzises Schrauben, Problemloser Langzeiteinsatz durch Sicherheitselektronik (permanente Überprüfung von Akku-Temperatur, Stromentnahme und Entladeschutz)</p>",
    amount: 2,
    img: "https://cdn.bueromarkt-ag.de/product/949fe7baf76eecfa6783fdd7b2d0f6529dfc6fe5-akku-bohrschrauber_dewalt_dcd791p2.jpg",
  },
  {
    id: 2,
    title: "Bosch Akku-Bohrschrauber GSR 18V-55, 18V",
    brand: "Bosch",
    price: 178,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>Akku-Bohrschrauber Bosch GSR 18V-55 Professional</h6><br><p>Kaufen Sie ein Bosch Professional 18V-Elektrowerkzeug&nbsp;über&nbsp;150 € (exkl. MwSt.) und erhalten Sie nach Registrierung auf https://www.bosch-professional.com/de/de/pro360/prodeals/ eine Prämie&nbsp;GRATIS dazu (siehe auch PDF Datenblatt).<br>----------------------------------------<br>Merkmale:<br>Akkuspannung: 18 V<br>Akku-Lieferumfang: 2 Akkus<br>Ladegerät: mit Ladegerät<br>----------------------------------------<br>weitere Produktinformationen:<br>Akkukapazität: 4,0Ah<br>Verwendung: Schrauben und Bohren<br>Drehmomentstufen: 20 + 1 Bohrstufe<br>Drehmoment weich: 28 Nm<br>Drehmoment hart: 55 Nm<br>Bohrfutterspannweite: 1,5-13 mm<br>Getriebe: 2 Gang<br>Drehzahl bis: 1750 U/min<br>Gewicht: 1 kg<br>Lieferung: inkl. 2x Akku ProCORE18V 4.0Ah, Schnellladegerät GAL 18V-40, Transportkoffer (L-BOXX 136)<br>----------------------------------------<br>sonstiges: für Arbeiten in Holz und Metall, mit bürstenlosem Motor für längere Werkzeuglebensdauer und höhere Akkulaufleistung, Electronic Motor Protection (EMP) schützt den Motor vor Überlastung</p>",
    amount: 1,
    img: "https://cdn.bueromarkt-ag.de/product/39acabbd90a5aa476a9f2e1cc18f24364302983e-akku-bohrschrauber_bosch_gsr_18v-55_professional.jpg",
  },
  {
    id: 3,
    title: "Etikettendrucker GG-D1200CW",
    brand: "G&G",
    price: 150,
    category: ["Bürobedarf", "Etikettendrucker"],
    desc: "<h6></h6><br><p></p>",
    amount: 4,
    img: "https://cdn.bueromarkt-ag.de/product/e9a3df937544cfd29258cb49c82ed5dceb51e07e-etikettendrucker_gg-image_gg-d1200cw.jpg",
  },
  {
    id: 4,
    title: "Stiftehalter Böttcher-AG Mesh Line, drehbar",
    brand: "Böttcher-AG",
    price: 253,
    category: ["Bürobedarf","Stiftehalter"],
    desc: "<h6>Stiftehalter Böttcher-AG Mesh Line, drehbar</h6><br><p>Praktischer Stiftehalter mit 7 Fächern<br>• Aus schwarzem und robustem&nbsp;Metalldraht<br>• Leichte Reinigung dank glatter Oberfläche<br>• Jederzeit alles nötige griffbereit<br>----------------------------------------<br>Merkmale:<br>Material: Metalldraht<br>Farbe: schwarz<br>Ausführung: drehbar<br>----------------------------------------<br>weitere Produktinformationen:<br>Fächeranzahl: 7 Fächer<br>Maße: 17,5 x 11 cm (ØxH)</p>",
    amount: 1,
    img: "https://cdn.bueromarkt-ag.de/product/436cba4db85c2582623e38506848849680ebafb9-stiftehalter_boettcher-ag_mesh_line_drehbar.jpg",
  },
  {
    id: 5,
    title: "Böttcher-AG H-8078F-2/1322 Bürostuhl",
    brand: "Böttcher-AG",
    price: 118,
    category: ["Stühle", "Bürobedarf"],
    desc: "<h6>Bürostuhl Böttcher-AG H-8078F-2/1322</h6><br><p>• Wippmechanik - einstellbar auf das Körpergewicht<br>• Muldensitz für optimale Unterstützung des Beckens<br>• Rückenlehne mit atmungsaktiver Netzbespannung<br>----------------------------------------<br>Merkmale:<br>Belastbarkeit: bis 120 kg<br>Bezug: Stoff, Netz<br>Farbe: schwarz<br>Armlehnenausführung: feste Armlehnen<br>----------------------------------------<br>weitere Produktinformationen:<br>Materialzusammensetzung: Stoff 100 % Polyester, Netz 100 % Polyester<br>empfohlene Sitzdauer: 6 Stunden/Tag<br>Sitztechnik: Wippmechanik<br>Sitzart: Muldensitz<br>Sitzgröße: 48 x 48 cm (BxT)<br>Sitzhöhenverstellung: 46 - 56 cm<br>Rückenlehnenhöhe: 48 cm<br>Fußkreuz: Kunststoff, verchromt<br>Rollen: Teppichbodenrollen<br>Lieferung: zerlegt</p>",
    amount: 1,
    img: "https://cdn.bueromarkt-ag.de/product/a55ecd22afc5d6f40a21027970856c9e2bd18e12-buerostuhl_boettcher-ag_h-8078f-21322.jpg",
  },
  {
    id: 6,
    title: "Kreide 100 Stück, Tafelkreide sortiert",
    brand: "Böttcher-AG",
    price: 7.50,
    category: ["Schreiben & Korrigieren"],
    desc: "<h6>Kreide 100 Stück, Tafelkreide sortiert</h6><br><p>• Runde Tafelkreide, 100 Stück im praktischen Karton<br>• Staubfrei, sandfrei, leicht abwischbar<br>• Gute Farbabgabe<br>----------------------------------------<br>Merkmale:<br>Ausführung: Tafelkreide<br>Farbe: farbig sortiert<br>Form: rund<br>----------------------------------------<br>weitere Produktinformationen:<br>Länge: 80 mm<br>Spitze: ungespitzt</p>",
    amount: 1,
    img: "https://cdn.bueromarkt-ag.de/product/5bd5311d335913bd55cdf55b86e4894d55e4de1c-kreide_boettcher-ag_100_stueck.jpg",
  },
  {
    id: 7,
    title: "Elba rado 81417 Hängeordner",
    brand: "DeWalt",
    price: 8.30,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>Hängeordner Elba 81417, rado, A4</h6><br><p>• Für die Hängeregistratur konzipiert, aber auch stehend verwendbar<br>• Mit einschiebbarem Hängebügel und metallgefasstem Griffloch<br>• Hebelmechanik mit Druckniederhalter<br>• Raumsparschlitze zur platzsparenden Archivierung<br>• Aus stabiler, Blauer Engel zertifizierter Hartpappe<br>----------------------------------------<br>Merkmale:<br>Format: A4<br>Ausführung: breit<br>----------------------------------------<br>weitere Produktinformationen:<br>Material: Hartpappe<br>Farbe: schwarz<br>Rückenbreite: 7,5 cm<br>Rückenschild: geklebt<br>Zertifikat: www.blauer-engel.de/uz56</p>",
    amount: 1,
    img: "https://cdn.bueromarkt-ag.de/product/75c1731474e63c4bd2a6bc42f5986f290a7502f7-haengeordner_elba_81417_rado_a4.jpg",
  },
];
