// import dewalt_dcd991nt from "./assets/products-img/dewalt_dcd991nt.png";
// import bohrschrauber from "./assets/products-img/bohrschrauber.png";
// import buerostuhl from "./assets/products-img/buerostuhl.png";
// import Elba from "./assets/products-img/Elba.png";
// import etikettendrucker from "./assets/products-img/etikettendrucker.png";
// import kreide_boettcherag_100_stueck from "./assets/products-img/kreide_boettcherag_100_stueck.png";
// import mesh_line_drehbar from "./assets/products-img/mesh_line_drehbar.png";
// import Brother from "./assets/products-img/Brother.png";
// import p2apple_ipad_air_2022 from "./assets/products-img/p2apple_ipad_air_2022.png";
// import rollcontainer from "./assets/products-img/rollcontainer.png";
// import tresorburg from "./assets/products-img/tresor_burg-waechter_pointsafe.png";
// import businesstrolley from "./assets/products-img/businesstrolley.png";
export const categories = [
  {
    id: 1,
    title: "Alle Kategorien",
  },
  {
    id: 2,
    title: "Bürobedarf",
  },
  {
    id: 3,
    title: "Papiere & Etiketten",
  },
  {
    id: 4,
    title: "Schreiben ",
  },
  {
    id: 5,
    title: "Verpackung",
  },
  {
    id: 6,
    title: "Präsentation",
  },
  {
    id: 7,
    title: "Druckerpatronen",
  },
  {
    id: 8,
    title: "Elektronik",
  },
  {
    id: 9,
    title: "Büromöbel",
  },
  {
    id: 10,
    title: "Lebensmittel",
  },
  {
    id: 11,
    title: "Werkzeug ",
  },
];

export const products = [
  {
    id: 1,
    title: "DeWalt Akku-Bohrschrauber DCD791P218V",
    brand: "DeWalt",
    price: 282,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>DeWalt DCD791P218V / 5,0Ah, mit 2 Akkus und Koffer</h6><br></br><p>Merkmale:<br>Akkuspannung: 18 V<br>Akku-Lieferumfang: 2 Akkus<br>Ladegerät: mit Ladegerät<br>----------------------------------------<br>weitere Produktinformationen:<br>Akkukapazität: 5,0Ah<br>Verwendung: Schrauben und Bohren<br>Drehmomentstufen: 15 + 1 Bohrstufe<br>Drehmoment weich: 27 Nm<br>Drehmoment hart: 70 Nm<br>Bohrfutterspannweite: 1,5-13 mm<br>Getriebe: 2 Gang<br>Drehzahl bis: 2000 U/min<br>Gewicht: 1,7 kg<br>Lieferung: inkl. 2x Akku, Schnellladegerät, Transportkoffer T STAK-Box<br>----------------------------------------<br>sonstiges: mit leuchtstarker LED, äußerst kompakte, ausbalancierte Bauweise mit geringem Gewicht, leicht dosierbare Schalterelektronik für exaktes Anbohren und präzises Schrauben, Problemloser Langzeiteinsatz durch Sicherheitselektronik (permanente Überprüfung von Akku-Temperatur, Stromentnahme und Entladeschutz)</p>",
    amount: 2,
    img: [
      img1: "https://cdn.bueromarkt-ag.de/product/9541906c312eefa06728d6cbce9ff60024ec4f8f-akku-bohrschrauber_dewalt_dcd791p2.jpg"
      ,
      img2: "https://cdn.bueromarkt-ag.de/product/b0a52b3cdfba68e627314c9f074445614ef86065-akku-bohrschrauber_dewalt_dcd791p2.jpg"
      ,
      img3: "https://cdn.bueromarkt-ag.de/product/40f3ab4dde75a262119583e931935d21237861f6-akku-bohrschrauber_dewalt_dcd791p2.jpg"
      ,
      img4: "https://cdn.bueromarkt-ag.de/product/949fe7baf76eecfa6783fdd7b2d0f6529dfc6fe5-akku-bohrschrauber_dewalt_dcd791p2.jpg"
     ,
      img5: "https://cdn.bueromarkt-ag.de/product/010b25814ebe4f1f443cc31b36cd407477002f66-akku-bohrschrauber_dewalt_dcd791p2.jpg"
    ],
    available: "Sofort lieferbar",
    sale: 0,
    onSale: "false",
    size: [""],
    color: [""],
  },
  {
    id: 2,
    title: "Bosch Akku-Bohrschrauber GSR 18V-55, 18V",
    brand: "Bosch",
    price: 178,
    category: ["Werkzeug & Baumarkt", "Akku-Bohrschrauber"],
    desc: "<h6>Akku-Bohrschrauber Bosch GSR 18V-55 Professional</h6><br><p>Kaufen Sie ein Bosch Professional 18V-Elektrowerkzeug&nbsp;über&nbsp;150 € (exkl. MwSt.) und erhalten Sie nach Registrierung auf https://www.bosch-professional.com/de/de/pro360/prodeals/ eine Prämie&nbsp;GRATIS dazu (siehe auch PDF Datenblatt).<br>----------------------------------------<br>Merkmale:<br>Akkuspannung: 18 V<br>Akku-Lieferumfang: 2 Akkus<br>Ladegerät: mit Ladegerät<br>----------------------------------------<br>weitere Produktinformationen:<br>Akkukapazität: 4,0Ah<br>Verwendung: Schrauben und Bohren<br>Drehmomentstufen: 20 + 1 Bohrstufe<br>Drehmoment weich: 28 Nm<br>Drehmoment hart: 55 Nm<br>Bohrfutterspannweite: 1,5-13 mm<br>Getriebe: 2 Gang<br>Drehzahl bis: 1750 U/min<br>Gewicht: 1 kg<br>Lieferung: inkl. 2x Akku ProCORE18V 4.0Ah, Schnellladegerät GAL 18V-40, Transportkoffer (L-BOXX 136)<br>----------------------------------------<br>sonstiges: für Arbeiten in Holz und Metall, mit bürstenlosem Motor für längere Werkzeuglebensdauer und höhere Akkulaufleistung, Electronic Motor Protection (EMP) schützt den Motor vor Überlastung</p>",
    amount: 1,
    img: [
      "https://cdn.bueromarkt-ag.de/product/3f0d3ab3ea40a909260d5b5bb4cd372714ec5655-akku-bohrschrauber_bosch_gsr_18v-55_professional.jpg",
      "https://cdn.bueromarkt-ag.de/product/43b3c16650a8e63c0b444f197ba6f7d5f49b2e0b-akku-bohrschrauber_bosch_gsr_18v-55_professional.jpg",
      "https://cdn.bueromarkt-ag.de/product/39acabbd90a5aa476a9f2e1cc18f24364302983e-akku-bohrschrauber_bosch_gsr_18v-55_professional.jpg",
      "https://cdn.bueromarkt-ag.de/product/34516113d6e1b408c5ef8e98be7386460cb10f09-akku-bohrschrauber_bosch_gsr_18v-55_professional.jpg",
    ],
    available: "Sofort lieferbar",
    sale: 0,
    onSale: "false",
    size: [""],
    color: [""],
  },
  {
    id: 3,
    title: "Etikettendrucker GG-image GG-D1200CW",
    brand: "G&G",
    price: 119,
    category: ["Bürobedarf", "Etikettendrucker"],
    desc: "<h6>etikettendrucker.webp</h6><br><p>• Leistungsstarker DHL-Etikettendrucker<br>• Bequem per App ansteuerbar<br>• Ideal für den Druck von DHL/UPS/DPD/Hermes/etc.-Versandaufklebern eignet<br>• Druckgeschwindigkeit: 120 mm/Sekunde<br>• Inklusive Cutter<br>----------------------------------------<br>Merkmale:<br>Schnittstelle: USB, Bluetooth<br>Drucktechnik: Thermodirekt<br>Ausführung: mit Barcodedruck<br>Druckhöhe: 104 mm<br>----------------------------------------<br>weitere Produktinformationen:<br>Etikettenhöhe: bis 105 mm<br>Medientypen: Einzel- oder Endlosetiketten mit oder ohne Reflexmarke, Endlosbelegpapier<br>Druckgeschwindigkeit: 120 mm/Sekunde<br>Druckauflösung: 203 x 203 dpi<br>Farbe: weiß<br>Maße: (BxHxT) 22,2 x 9,2 x 10,5 cm<br>Lieferung: inkl. USB-Kabel<br>----------------------------------------<br>sonstiges: Etikettendesigns können individuell per App erstellt werden</p>",
    amount: 4,
    img: [
      "https://cdn.bueromarkt-ag.de/product/e9a3df937544cfd29258cb49c82ed5dceb51e07e-etikettendrucker_gg-image_gg-d1200cw.jpg",
      "https://cdn.bueromarkt-ag.de/product/2f6b47d26c0f455b7edd4a6f13bf1d8858fab05b-etikettendrucker_gg-image_gg-d1200cw.jpg",
      "https://cdn.bueromarkt-ag.de/product/0a4794722cf893efb97e6fe5fe7d28b8412fe494-etikettendrucker_gg-image_gg-d1200cw.jpg",
      "https://cdn.bueromarkt-ag.de/product/2f6b47d26c0f455b7edd4a6f13bf1d8858fab05b-etikettendrucker_gg-image_gg-d1200cw.jpg",
    ],
    available: "Sofort lieferbar",
    sale: 0,
    onSale: "false",
    size: [""],
    color: [""],
  },
  {
    id: 4,
    title: "Stiftehalter Böttcher-AG Mesh Line, drehbar",
    brand: "Böttcher-AG",
    price: 253,
    category: ["Bürobedarf", "Stiftehalter"],
    desc: "<h6>Stiftehalter Böttcher-AG Mesh Line, drehbar</h6><br><p>Praktischer Stiftehalter mit 7 Fächern<br>• Aus schwarzem und robustem&nbsp;Metalldraht<br>• Leichte Reinigung dank glatter Oberfläche<br>• Jederzeit alles nötige griffbereit<br>----------------------------------------<br>Merkmale:<br>Material: Metalldraht<br>Farbe: schwarz<br>Ausführung: drehbar<br>----------------------------------------<br>weitere Produktinformationen:<br>Fächeranzahl: 7 Fächer<br>Maße: 17,5 x 11 cm (ØxH)</p>",
    amount: 1,
    img: [
      "https://cdn.bueromarkt-ag.de/product/436cba4db85c2582623e38506848849680ebafb9-stiftehalter_boettcher-ag_mesh_line_drehbar.jpg",
      "https://cdn.bueromarkt-ag.de/product/86060f7d8215e4b2d9b02894f42bc127dcbfcb29-stiftehalter_boettcher-ag_mesh_line_drehbar.jpg",
      "https://cdn.bueromarkt-ag.de/product/7eac1782823aad497bf918315449f6ad074bfdef-stiftehalter_boettcher-ag_mesh_line_drehbar.jpg",
      "https://cdn.bueromarkt-ag.de/product/37922b4ecb61a58e168a02868254eb622d5550b3-stiftehalter_boettcher-ag_mesh_line_drehbar.jpg",
    ],
    available: "Sofort lieferbar",
    sale: 0,
    onSale: "true",
    size: [""],
    color: [""],
  },
  {
    id: 5,
    title: "Böttcher-AG H-8078F-2/1322 Bürostuhl",
    brand: "Böttcher-AG",
    price: 118,
    category: ["Stühle", "Bürobedarf"],
    desc: "<h6>Bürostuhl Böttcher-AG H-8078F-2/1322</h6><br><p>• Wippmechanik - einstellbar auf das Körpergewicht<br>• Muldensitz für optimale Unterstützung des Beckens<br>• Rückenlehne mit atmungsaktiver Netzbespannung<br>----------------------------------------<br>Merkmale:<br>Belastbarkeit: bis 120 kg<br>Bezug: Stoff, Netz<br>Farbe: schwarz<br>Armlehnenausführung: feste Armlehnen<br>----------------------------------------<br>weitere Produktinformationen:<br>Materialzusammensetzung: Stoff 100 % Polyester, Netz 100 % Polyester<br>empfohlene Sitzdauer: 6 Stunden/Tag<br>Sitztechnik: Wippmechanik<br>Sitzart: Muldensitz<br>Sitzgröße: 48 x 48 cm (BxT)<br>Sitzhöhenverstellung: 46 - 56 cm<br>Rückenlehnenhöhe: 48 cm<br>Fußkreuz: Kunststoff, verchromt<br>Rollen: Teppichbodenrollen<br>Lieferung: zerlegt</p>",
    amount: 1,
    img: [
      "https://cdn.bueromarkt-ag.de/product/a55ecd22afc5d6f40a21027970856c9e2bd18e12-buerostuhl_boettcher-ag_h-8078f-21322.jpg",
      "https://cdn.bueromarkt-ag.de/product/7aa720656fee4250758401610b54c96e7329019d-buerostuhl_boettcher-ag_h-8078f-21322.jpg",
      "https://cdn.bueromarkt-ag.de/product/89801f4a4af38cdc019a351b2b71c39e9f75f7bf-buerostuhl_boettcher-ag_h-8078f-21322.jpg",
      "https://cdn.bueromarkt-ag.de/product/bf43b0efe1c31e9d0eef75f480f297433c9be272-buerostuhl_boettcher-ag_h-8078f-21322.jpg",
    ],
    available: "Sofort lieferbar",
    sale: 0,
    onSale: "false",
    size: [""],
    color: [""],
  },
  {
    id: 6,
    title: "Canon Multifunktionsgerät Pixma TS5150 BLACK",
    brand: "Canon",
    price: 7.5,
    category: ["Multifunktionsgerät", "Elektronik", "Computer"],
    desc: "Merkmale:<br>Ausführung: Tintenstrahl, 3 in 1<br>Format bis: A4<br>Funktion: Drucker, Kopierer, Scanner<br>Schnittstelle: Apple AirPrint, Google Cloud Print, USB, WLAN<br>Eigenschaft: Duplex-Druck, mobiles Drucken<br>----------------------------------------<br>weitere Produktinformationen:<br>Drucktechnik: Tinte<br>Display: 6,2 cm Farbdisplay<br>Papiervorrat: 20 Blatt Fotopapier, 100 Blatt Kassette<br>Treiber: Windows 7 oder neuer, Mac OS X 10.10.5 oder neuer<br>Farbdrucker<br>Druck/Min.: s/w 13, farbig 6,8 ISO-Seiten, max. Auflösung: 4800 x 1200dpi<br>Farbkopierer<br>Druck/Min.: s/w 4, farbig 3 ISO-Seiten, Kopienvorwahl: 1-99, Zoom: 25% - 400%<br>Farbscanner<br>Typ: Flachbett, Auflösung: bis 1.200 x 2.400dpi<br>Maße: 42,5 x 31,5 x 14,7 cm (BxTxH)<br>Lieferung: inkl. Tintenpatronen, Netzkabel, Software auf CD, Lieferung ohne USB-Kabel (Art.Nr.45021)<br>----------------------------------------<br>sonstiges: Wi-Fi Direct, Bluetooth, randloser Druck bis A4,<br>Verbrauchsmaterialien: 2x Tintenpatronen je 1x Schwarz, Farbe",
    amount: 1,
    img: [
      "https://cdn.bueromarkt-ag.de/product/87dae8b24693d1208673bf8587fc43d593eb6074-multifunktionsgeraet_canon_pixma_ts5150_black.jpg",
      "https://cdn.bueromarkt-ag.de/product/ac0a61291bcfda165520e1832965b6431c7a675e-multifunktionsgeraet_canon_pixma_ts5150_black.jpg",
      "https://cdn.bueromarkt-ag.de/product/74d887d507646cbc674fa20eddbd727bd8041313-multifunktionsgeraet_canon_pixma_ts5150_black.jpg",
    ],
    available: "Derzeit nicht verfügbar",
    sale: 0,
    onSale: "false",
    size: [""],
    color: ["black"],
  },
  {
    id: 7,
    title: "Elba rado 81417 Hängeordner",
    brand: "Elba",
    price: 8.3,
    category: ["Hängeordner", "Bürobedarf", "Papiere & Etiketten"],
    desc: "<h6>Hängeordner Elba 81417, rado, A4</h6><br><p>• Für die Hängeregistratur konzipiert, aber auch stehend verwendbar<br>• Mit einschiebbarem Hängebügel und metallgefasstem Griffloch<br>• Hebelmechanik mit Druckniederhalter<br>• Raumsparschlitze zur platzsparenden Archivierung<br>• Aus stabiler, Blauer Engel zertifizierter Hartpappe<br>----------------------------------------<br>Merkmale:<br>Format: A4<br>Ausführung: breit<br>----------------------------------------<br>weitere Produktinformationen:<br>Material: Hartpappe<br>Farbe: schwarz<br>Rückenbreite: 7,5 cm<br>Rückenschild: geklebt<br>Zertifikat: www.blauer-engel.de/uz56</p>",
    amount: 9,
    img: [
      "https://cdn.bueromarkt-ag.de/product/75c1731474e63c4bd2a6bc42f5986f290a7502f7-haengeordner_elba_81417_rado_a4.jpg",
      "https://cdn.bueromarkt-ag.de/product/4ec37ef2eadf4303680a9c58697241e1ed953460-haengeordner_elba_81417_rado_a4.jpg",
      "https://cdn.bueromarkt-ag.de/product/5fe842830fbe4154a94084f5d21e67d5a19d6f87-haengeordner_elba_81417_rado_a4.jpg",
      "https://cdn.bueromarkt-ag.de/product/8f1a4cf4745b829402dd43f72b366f0282884563-haengeordner_elba_81417_rado_a4.jpg",
    ],
    available: "Sofort lieferbar",
    sale: 0,
    onSale: "false",
    size: ["a4"],
    color: ["black"],
  },
  {
    id: 8,
    title: "Brother MFC L3750CDW Multifunktionsgerät",
    brand: "Brother",
    price: 478,
    category: ["Multifunktionsgerät", "Elektronik", "Computer"],
    desc: "<h6>Multifunktionsgerät Brother MFC L3750CDW</h6><br><p>Merkmale:<br>Ausführung: Farblaser, 4 in 1<br>Format bis: A4<br>Funktion: Drucker, Fax, Kopierer, Scanner<br>Schnittstelle: Apple AirPrint, Google Cloud Print, USB, LAN, WLAN<br>Eigenschaft: ADF, Duplex-Druck, mobiles Drucken<br>----------------------------------------<br>weitere Produktinformationen:<br>Drucktechnik: LED<br>Display: 9,3 cm Touchscreen-Farbdisplay<br>Druckvolumen: max. 30.000 Seiten/Monat, empfohlen bis 1.500 Seiten/Monat<br>Papiervorrat: 250 Blatt Kassette<br>Automatischer Dokumenteneinzug: 50 Blatt<br>Treiber: Windows 7 oder neuer, Mac OS X 10.11.6 oder neuer<br>Farbdrucker<br>Druck/Min.: s/w 24, farbig 24 Seiten, max. Auflösung: 2400 x 600dpi<br>Farbkopierer<br>Kopienvorwahl: 1-99, Zoom: 25% - 400%<br>Farbscanner<br>Typ: Flachbett, Einzug, Auflösung: 2400 x 1200dpi<br>Farbfax<br>Geschwindigkeit: 33600 bps, Speicher: 500 Seiten<br>Maße: (BxTxH) 41 x 47,5 x 41,4 cm<br>green-Aspekt: Energy Star - energiesparend<br>Garantie: 3 Jahre Herstellergarantie Vor-Ort<br>Lieferung: inkl. Toner, Netzkabel, Lieferung ohne Fax- und USB-Kabel<br>----------------------------------------<br>sonstiges: USB-Host, WiFi-Direct</p>",
    amount: 26,
    img: [
      "https://cdn.bueromarkt-ag.de/product/621a4b0a2121c13416cffd077d79e1db5bfe527b-multifunktionsgeraet_brother_mfc_l3750cdw.jpg",
      "https://cdn.bueromarkt-ag.de/product/56e64da7081a926ab17854cb835510f2b679bb3a-multifunktionsgeraet_brother_mfc_l3750cdw.jpg",
      "https://cdn.bueromarkt-ag.de/product/2c7806d401530085d8297ec62b2bec48c7193a01-multifunktionsgeraet_brother_mfc_l3750cdw.jpg",
    ],
    available: ["Sofort lieferbar", "badge style-2 consistent"],
    sale: 20,
    onSale: "true",
    size: [""],
    color: [""],
  },
  {
    id: 9,
    title: "Apple Tablet-PC iPad Air 2022 MM9E3FD",
    brand: "Apple",
    price: 780,
    category: ["Tablet", "Elektronik"],
    desc: "<h6>Tablet-PC Apple iPad Air 2022 MM9E3FD</h6><br><p>• Liquid Retina Display und True Tone für mehr Details und Farben<br>• Produktiveres Arbeiten dank neuem M1 Chip mit Neural Engine<br>• Bestens ausgestattet für das digitale Klassenzimmer oder Homeoffice<br>• Facetime Frontkamera mit 12MP und praktischem Folgemodus<br>• Mit schneller &amp; sicherer Touch ID für sicheres Authentifizieren und Apple Pay<br>• Unterstützung für Magic Keyboard, Smart Keyboard Folio und Apple Pencil<br>----------------------------------------<br>Merkmale:<br>Modellreihe: iPad Air 2022<br>Displaygröße: 10,9 Zoll<br>Betriebssystem: Apple iPadOS<br>Kommunikation: WLAN<br>interner Speicher: 64 GB<br>----------------------------------------<br>weitere Produktinformationen:<br>Display: 10,9 Zoll / 27,69cm, Liquid Retina Display, Multi-Touchfunktion, True Tone<br>Bildauflösung: 2360 x 1640 Pixel bei 264 ppi<br>Prozessor: Apple M1 Chip, 8-Core CPU, 8-Core Grafik, Neural Engine<br>Arbeitsspeicher: 8 GB<br>Kamera (integriert): Frontkamera 12 MP, Rückkamera 12 MP<br>Kommunikation: WLAN 802.11a/b/g/n/ac/ax, Wi-Fi 6, Bluetooth 5.0<br>Anschlüsse: USB-C 3.1<br>Funktionen: WLAN-Internet, E-Mail, Video-/ Bilder- und Musikwiedergabe, Apple-Anwendungen, unterstützt den Apple Pencil 2.Generation<br>Akkutyp: Lithium-Polymer mit 28,6 Watt&shy;stunden<br>Farbe: blau<br>Maße: (BxHxT) 17,8 x 24,7 x 0,6 cm<br>Gewicht: 461 g<br>green-Aspekt: Energy Star<br>Lieferung: inkl. USB-C Power Adapter (Netzteil), USB-C-Ladekabel</p>",
    amount: 17,
    img: [
      "https://cdn.bueromarkt-ag.de/product/96d65a150d41445d21b5774ce5555738e474273f-tablet-pc_apple_ipad_air_2022_mm9e3fda_wifi.jpg",
      "https://cdn.bueromarkt-ag.de/product/900684dab20eaba36f11c23542e20cd33d5fcd9e-tablet-pc_apple_ipad_air_2022_mm9e3fda_wifi.jpg",
      "https://cdn.bueromarkt-ag.de/product/9ae4eb0d8429637b35ddf236863d73e1c8dfaefa-tablet-pc_apple_ipad_air_2022_mm9e3fda_wifi.jpg",
      "https://cdn.bueromarkt-ag.de/product/ecf21946ce3d08c1a7a57724e0191ef5fd586d91-tablet-pc_apple_ipad_air_2022_mm9e3fda_wifi.jpg",
    ],
    available: ["Bestpreis", "badge  best"],
    sale: 19,
    onSale: "true",
    size: [""],
    color: [""],
  },
  {
    id: 10,
    title: "Rollcontainer FlexiSpot CB8",
    brand: "FlexiSpot",
    price: 214,
    category: ["Rollcontainer", "Bürobedarf"],
    desc: "<h6>Rollcontainer FlexiSpot CB8, Metall,schwarzmit 2 Schüben, abschließbar</h6><br><p>• Schlichtes Design mit abgerundeten Ecken &amp; glatten Kanten<br>----------------------------------------<br>Merkmale:<br>Farbe: schwarz<br>Ausführung: abschließbar, mit Schubladen<br>Material: Metall<br>----------------------------------------<br>weitere Produktinformationen:<br>Schließung: mit Zentralverschluss<br>Ausstattung: 2 Schübe<br>Tragkraft der Schübe: 20 kg<br>Griffe: Muldengriffe<br>Leichtlaufrollen: 4, 2 davon feststellbar<br>Maße: (BxHxT) 40 x 50 x 40 cm<br>Lieferung: montiert<br>Lieferung direkt ab Werk!<br>----------------------------------------<br>sonstiges: Schübe auf Teleskop-Auszügen, Stützrolle am unteren Schub</p>",
    amount: 16,
    img: [
      "https://cdn.bueromarkt-ag.de/product/e71d1f65e029fa38576aa82ba96a603951899833-rollcontainer_flexispot_cb8_metall_schwarz.jpg",
      "https://cdn.bueromarkt-ag.de/product/a5cdc9317cb689f464bb029d985ecd1d2fa3bf3a-rollcontainer_flexispot_cb8_metall_schwarz.jpg",
      "https://cdn.bueromarkt-ag.de/product/6bcf0b30d227182499c477b3c67590544869ca52-rollcontainer_flexispot_cb8_metall_schwarz.jpg",
    ],
    available: "",
    sale: 29,
    onSale: "true",
    size: ["(BxHxT) 40 x 50 x 40 cm"],
    color: ["black"],
  },
  {
    id: 11,
    title: "Wenger Business-Trolley Patriot 2",
    brand: "Wenger",
    price: 148,
    category: ["Koffer", "Rucksäcke", "Taschen"],
    desc: "<h6>Business-Trolley Wenger Patriot 2</h6><br><p>• Gepolstertes Fach für Laptops bis 17 Zoll<br>• Herausnehmbare Laptoptasche für Laptops bis 15,6 Zoll<br>• 1 Fach für Kleidung (Overnight-Funktion)<br>• Reißverschlussfächer, Handytasche und Stifthalter<br>• Ergonomischer Tragegriff und stabiler Standfuß<br>• Teleskopstange mit mehreren Längenstufen<br>• Leichtlaufrollen perfekt für enge Kurven und schmale Gänge<br>• Abschließbare Reißverschlüsse<br>----------------------------------------<br>Merkmale:<br>Größe: S (bis 56 cm), Handgepäck<br>Ausführung: Laptopfach<br>Material: Polyester<br>Farbe: schwarz<br>----------------------------------------<br>weitere Produktinformationen:<br>Verschluss: Reißverschluss<br>Laptopfach: bis 15,4 Zoll<br>Gewicht: 4,1 kg<br>Maße: 43 x 41 x 31 cm (BxHxT)<br>Garantie: 3 Jahre Herstellergarantie<br>----------------------------------------<br>sonstiges: 1 Hauptfach mit Einschubfächern für A4 Dokumente, 1 zusätzliches Reißverschlussfach außen</p>",
    amount: 9,
    img: [
      "https://cdn.bueromarkt-ag.de/product/bffb30903b7ab4402e8206c541e6c8d106147ae8-business-trolley_wenger_patriot_2_600662.jpg",
      "https://cdn.bueromarkt-ag.de/product/512e62565f9e9588567d2488e4a254c0d24cd16c-business-trolley_wenger_patriot_2_600662.jpg",
      "https://cdn.bueromarkt-ag.de/product/7fdf6208a93c33547d618c095faa6d8d323bca61-business-trolley_wenger_patriot_2_600662.jpg",
    ],
    available: ["Empfehlen", "badge style-2 recommend"],
    sale: 10,
    onSale: "true",
    size: [""],
    color: [""],
  },
  {
    id: 12,
    title: "Burg-Wächter Tresor PointSafe P 2 E FS",
    brand: "Burg-Wächter",
    price: 223,
    category: ["Büromöbel", "Stahlschränke"],
    desc: "<h6>Tresor Burg-Wächter PointSafe P 2 E FS</h6><br><p>Merkmale:<br>Funktion: Möbeltresor<br>Ausführung: biometrisch, mit Zahlenschloss<br>Schloss: Fingerabdruck, Elektronikschloss<br>Höhe: 25,5 cm<br>----------------------------------------<br>weitere Produktinformationen:<br>Außenmaß: 25,5 x 35 x 30 cm (HxBxT)<br>Innenmaß: 24,8 x 34,3 x 24,1 cm (HxBxT)<br>Türdurchgangsmaß: 18,8 x 23 cm (HxB)<br>Volumen: 20,5 Liter<br>Gewicht: 14 kg<br>Fächer: 2<br>Farbe: schwarz<br>Bodenverankerung: vorgerichtet für Rückwand- und Bodenverankerung inkl. Verankerungsmaterial<br>Lieferung: inkl. Befestigungsmaterial, Batterien (4x AA), einen Schlüssel zur mechanischen Notöffnung<br>----------------------------------------<br>sonstiges: einwandiger Korpus und doppelwandige Tür, einseitige Verriegelung durch massive 22mm starke Rundbolzen, Elektronik-Zahlenschloss mit General- und Benutzercode, Speicherung von bis zu 5 verschiedenen Fingerabdrücken, herausnehmbarer Fachboden, geeignet für die Aufbewahrung von Dokumenten aus Papier und Wertgegenständen, sowie Speichermedien</p>",
    amount: 19,
    img: [
      "https://cdn.bueromarkt-ag.de/product/4f3d13e397071329089fd81928bc961ae492521a-tresor_burg-waechter_pointsafe_p_2_e_fs.jpg",
      "https://cdn.bueromarkt-ag.de/product/24946fd4757b25c83143cdde0f4ecf6a3c5c9c96-tresor_burg-waechter_pointsafe_p_2_e_fs.jpg",
      "https://cdn.bueromarkt-ag.de/product/f07bfa643ebeb375b1e0e3f1408bfea40894a5d7-tresor_burg-waechter_pointsafe_p_2_e_fs.jpg",
      "https://cdn.bueromarkt-ag.de/product/fbbe47e512a54f756db33ba95a15af068a899676-tresor_burg-waechter_pointsafe_p_2_e_fs.jpg",
    ],
    available: "",
    sale: 20,
    onSale: "true",
    size: [""],
    color: [""],
  },
];
